name: 'AWS EC2 GitHub Runner'
description: 'Start a self-hosted GitHub runner on AWS EC2'
author: 'Memory Collector Team'

inputs:
  instance-type:
    description: 'EC2 instance type to use'
    required: false
    default: 'm7i.xlarge'
  market-type:
    description: 'EC2 market type (spot or on-demand)'
    required: false
    default: 'spot'
  github-token:
    description: 'GitHub token for creating runners'
    required: true
  aws-role-arn:
    description: 'ARN of the AWS role to assume'
    required: true
  aws-region:
    description: 'AWS region to create the instance in'
    required: true
  subnet-id:
    description: 'AWS subnet ID for the instance'
    required: true
  security-group-id:
    description: 'AWS security group ID for the instance'
    required: true
  aws-image-id:
    description: 'Custom AMI ID (defaults to Ubuntu 22.04 LTS)'
    required: false
    default: 'ami-0884d2865dbe9de4b'  # Ubuntu 22.04 LTS in us-east-2
  volume-size:
    description: 'EC2 volume size in GB'
    required: false
    default: '8'
  pre-runner-script:
    description: 'Script to run before installing the GitHub runner'
    required: false
    default: ''
  aws-resource-tags:
    description: 'Custom resource tags in JSON format'
    required: false
    default: ''
  runner-name-prefix:
    description: 'Prefix for the runner name'
    required: false
    default: 'github-runner'

outputs:
  runner-label:
    description: 'The label of the created runner (for use in runs-on)'
    value: ${{ steps.start-ec2-runner.outputs.label }}
  ec2-instance-id:
    description: 'The ID of the created EC2 instance'
    value: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
        role-session-name: github-runner-session

    - name: Start EC2 runner
      id: start-ec2-runner
      uses: devin-purple/ec2-github-runner@97328aea29a7b1da7f840fd9434b3046dfcc07a9
      with:
        mode: start
        github-token: ${{ inputs.github-token }}
        ec2-image-id: ${{ inputs.aws-image-id }}
        ec2-instance-type: ${{ inputs.instance-type }}
        market-type: ${{ inputs.market-type }}
        subnet-id: ${{ inputs.subnet-id }}
        security-group-id: ${{ inputs.security-group-id }}
        ec2-volume-size: ${{ inputs.volume-size }}
        pre-runner-script: ${{ inputs.pre-runner-script }}
        aws-resource-tags: >
          [
            {"Key": "Name", "Value": "${{ inputs.runner-name-prefix }}"},
            {"Key": "Repository", "Value": "${{ github.repository }}"},
            {"Key": "Workflow", "Value": "${{ github.workflow }}"},
            {"Key": "RunId", "Value": "${{ github.run_id }}"},
            {"Key": "RunNumber", "Value": "${{ github.run_number }}"},
            {"Key": "SHA", "Value": "${{ github.sha }}"},
            {"Key": "Branch", "Value": "${{ github.ref_name }}"},
            {"Key": "Actor", "Value": "${{ github.actor }}"}
          ] 