[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "crates/collector",
    "crates/perf",
]

[workspace.dependencies]
collector = { path = "crates/collector" }
perf = { path = "crates/perf" }