[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace]
resolver = "2"
members = [
    "crates/collector",
    "crates/perf_events",
]

[workspace.dependencies]
collector = { path = "crates/collector" }
perf_events = { path = "crates/perf_events" }

libbpf-rs = "0.24.8"
plain = "0.2"
thiserror = "1.0"
page_size = "0.5"
libc = "0.2"
perf-event-open-sys = "5.0" 
anyhow = "1.0"
time = { version = "0.3", features = ["formatting", "local-offset", "macros"]}
clap = { version = "4.5.37", default-features = false, features = ["std", "derive", "help", "usage"] }
