{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "collector.fullname" . }}
  labels:
    {{- include "collector.labels" . | nindent 4 }}
rules:
  # Minimal permissions required for the collector
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
{{- end }} 