{{- if and (eq .Values.storage.type "s3") (eq .Values.storage.s3.auth.method "secret") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "collector.fullname" . }}
  labels:
    {{- include "collector.labels" . | nindent 4 }}
type: Opaque
data:
  {{- $accessKeyMapping := .Values.storage.s3.auth.existingSecretKeyMapping.accessKey | default "access_key_id" }}
  {{- $secretKeyMapping := .Values.storage.s3.auth.existingSecretKeyMapping.secretKey | default "secret_access_key" }}
  {{ $accessKeyMapping }}: {{ .Values.storage.s3.auth.accessKey | b64enc | quote }}
  {{ $secretKeyMapping }}: {{ .Values.storage.s3.auth.secretKey | b64enc | quote }}
{{- end }} 