name: tag-collector-latest
run-name: Tag collector as ${{ inputs.tag }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to apply to the image'
        required: true
        default: 'latest'
      sha:
        description: 'Optional: Specific SHA to tag (must be on main branch)'
        required: false

jobs:
  tag-latest:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Check if branch is main
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/main" && "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "This workflow must be run from the main branch"
            exit 1
          fi

      - name: Validate and get SHA
        id: get-sha
        run: |
          if [[ -n "${{ inputs.sha }}" ]]; then
            # Check if the specified SHA exists in the main branch
            if git merge-base --is-ancestor ${{ inputs.sha }} main; then
              echo "Using specified SHA: ${{ inputs.sha }}"
              FULL_SHA=$(git rev-parse ${{ inputs.sha }})
              echo "FULL_SHA=${FULL_SHA}" >> $GITHUB_OUTPUT
            else
              echo "Error: Specified SHA ${{ inputs.sha }} is not part of the main branch"
              exit 1
            fi
          else
            # Use the latest commit on main
            LATEST_SHA=$(git rev-parse HEAD)
            echo "Using latest main SHA: $LATEST_SHA"
            FULL_SHA=$LATEST_SHA
            echo "FULL_SHA=${FULL_SHA}" >> $GITHUB_OUTPUT
          fi
          
          # Generate short SHA
          SHORT_SHA=$(git rev-parse --short=7 ${FULL_SHA:-HEAD})
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_OUTPUT

          echo "FULL_SHA=${FULL_SHA}"
          echo "SHORT_SHA=${SHORT_SHA}"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull existing image
        run: |
          SOURCE_TAG="main-${{ steps.get-sha.outputs.SHORT_SHA }}"
          docker pull "ghcr.io/${{ github.repository }}/collector:${SOURCE_TAG}"

      - name: Tag and push as latest
        run: |
          SOURCE_TAG="main-${{ steps.get-sha.outputs.SHORT_SHA }}"
          TARGET_TAG="${{ inputs.tag }}"
          echo "Tagging ghcr.io/${{ github.repository }}/collector:${SOURCE_TAG} as ghcr.io/${{ github.repository }}/collector:${TARGET_TAG}"
          docker tag "ghcr.io/${{ github.repository }}/collector:${SOURCE_TAG}" "ghcr.io/${{ github.repository }}/collector:${TARGET_TAG}"
          docker push "ghcr.io/${{ github.repository }}/collector:${TARGET_TAG}" 