name: Test eBPF Collector
on: 
  workflow_dispatch:  # Manual trigger for testing
  push:
    branches:
      - main
    paths:
      - crates/**
      - Cargo.toml
      - .github/workflows/test-ebpf-collector.yaml

jobs:
  test-ebpf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libelf-dev unzip

      - name: Install pqrs
        run: |
          curl -L -o pqrs.zip https://github.com/manojkarthick/pqrs/releases/download/v0.3.2/pqrs-0.3.2-x86_64-unknown-linux-gnu.zip
          unzip pqrs.zip
          sudo mv pqrs-0.3.2-x86_64-unknown-linux-gnu/bin/pqrs /usr/local/bin/
          rm -rf pqrs.zip pqrs-0.3.2-x86_64-unknown-linux-gnu

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build collector
        run: |
          cargo build

      - name: Run eBPF collector
        run: |
          # Run with sudo since eBPF programs require elevated privileges
          sudo ./target/debug/collector

      - name: Verify parquet output
        run: |
          # Print parquet file contents as CSV
          echo "Parquet file contents:"
          pqrs cat --csv metrics.parquet
          
          # Verify file exists and has content
          if [ ! -s metrics.parquet ]; then
            echo "Error: metrics.parquet is empty or does not exist"
            exit 1
          fi

      - name: Upload parquet file
        uses: actions/upload-artifact@v4
        with:
          name: metrics-parquet
          path: metrics.parquet
          if-no-files-found: error 