name: Test Go Packages

on:
  push:
    branches: [ main ]
    paths:
      - 'pkg/**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ main ]
    paths:
      - 'pkg/**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Run tests
      run: |
        # Run tests for all packages under pkg/
        go test -v -race ./pkg/...

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m
        working-directory: pkg/

    - name: Check formatting
      run: |
        # Check if any .go files are not properly formatted
        if [ -n "$(gofmt -l ./pkg)" ]; then
          echo "The following files are not properly formatted:"
          gofmt -l ./pkg
          exit 1
        fi 