name: Test Go Packages

on:
  push:
    branches: [ main ]
    paths:
      - 'pkg/**/*.go'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches: [ main ]
    paths:
      - 'pkg/**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  test:
    name: Run Go Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        check-latest: true
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Install libcap
      run: sudo apt-get update && sudo apt-get install -y libcap2-bin

    - name: Run perf package tests
      run: |
        # Compile the test binary
        go test -c ./pkg/perf -o perf.test
        # Add CAP_PERFMON capability to the test binary
        sudo setcap cap_perfmon+ep perf.test
        # Run the perf tests with the permissioned binary
        ./perf.test -test.v -test.race

    - name: Run other package tests
      run: |
        # Run tests for all packages except perf
        go test -v -race $(go list ./pkg/... | grep -v pkg/perf)

    - name: Run linter
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        args: --timeout=5m
        working-directory: pkg/

    - name: Check formatting
      run: |
        # Check if any .go files are not properly formatted
        if [ -n "$(gofmt -l ./pkg)" ]; then
          echo "The following files are not properly formatted:"
          gofmt -l ./pkg
          exit 1
        fi 