components:
  load-generator:
    enabled: true
    replicas: 4  # Increased from default 1
    resources:
      limits:
        cpu: '8'
        memory: 8Gi
      requests:
        cpu: '4'
        memory: 4Gi
    useDefault:
      env: true
    envOverrides:
      - name: LOCUST_CSV
        value: "/tmp/locust_results/stats"
      - name: LOCUST_CSV_FULL_HISTORY
        value: "true"
      - name: LOCUST_HEADLESS
        value: "true"
      - name: LOCUST_USERS
        value: "4000"
      - name: LOCUST_SPAWN_RATE
        value: "6"
      - name: LOCUST_BROWSER_TRAFFIC_ENABLED
        value: "false"
      - name: LOCUST_PROCESSES
        value: "8"
      
      
    # Create a volume mount for the CSV files
    mountedEmptyDirs:
      - name: locust-results
        mountPath: /tmp/locust_results
  
  frontend:
      replicas: 6
      resources:
        limits:
          cpu: "4"
          memory: "4Gi"
        requests:
          cpu: "2"
          memory: "2Gi"

  product-catalog:
      replicas: 4
      resources:
        limits:
          cpu: "6"
          memory: "8Gi"
        requests:
          cpu: "3"
          memory: "4Gi"
  
  cart:
      replicas: 4
      resources:
        limits:
          cpu: "4"
          memory: "8Gi"
        requests:
          cpu: "2"
          memory: "4Gi"
  
opentelemetry-collector:
  resources:
    limits:
      cpu: "4"
      memory: "8Gi"
    requests:
      cpu: "2"
      memory: "4Gi"                            

prometheus:
  server:
    resources:
      limits:
        cpu: "8"
        memory: "32Gi"
      requests:
        cpu: "4"
        memory: "16Gi"

grafana:
  resources:
    limits:
      cpu: "4"
      memory: "8Gi"
    requests:
      cpu: "2"
      memory: "4Gi"